municipality_neighbours = {
        "Akaa": ['Hämeenlinna', 'Lempäälä', 'Urjala', 'Valkeakoski', 'Vesilahti'] ,
        "Alajärvi": ['Alavus', 'Kuortane', 'Kyyjärvi', 'Lappajärvi', 'Lapua', 'Soini', 'Vimpeli', 'Ähtäri'] ,
        "Alavieska": ['Kalajoki', 'Merijärvi', 'Oulainen', 'Ylivieska'] ,
        "Alavus": ['Alajärvi', 'Kuortane', 'Seinäjoki', 'Virrat', 'Ähtäri'] ,
        "Asikkala": ['Hämeenkoski', 'Lammi', 'Nastola'] ,
        "Enontekiö": ['Inari', 'Kittilä', 'Muonio'] ,
        "Espoo": ['Vihti', 'Nurmijärvi', 'Vantaa', 'Helsinki', 'Kirkkonummi', 'Kauniainen'] ,
        "Eurajoki": ['Eura', 'Nakkila', 'Pori', 'Rauma'] ,
        "Evijärvi": ['Kauhava', 'Kruunupyy', 'Lappajärvi', 'Veteli'] ,
        "Haapajärvi": ['Haapavesi', 'Kärsämäki', 'Nivala', 'Pihtipudas', 'Pyhäjärvi', 'Reisjärvi', 'Sievi'] ,
        "Hailuoto": ['Lumijoki', 'Oulu', 'Siikajoki'] ,
                'Hamina': ['Kotka', 'Kouvola', 'Luumäki', 'Miehikkälä', 'Virolahti'],
        "Hartola": ['Heinola', 'Joutsa', 'Luhanka', 'Pertunmaa', 'Sysmä'] ,
        "Hausjärvi": ['Hyvinkää', 'Hämeenlinna', 'Hollola', 'Janakkala', 'Kärkölä', 'Mäntsälä', 'Riihimäki'] ,
        "Heinola": ['Asikkala', 'Hartola', 'Iitti', 'Kouvola', 'Lahti', 'Mäntyharju', 'Pertunmaa', 'Sysmä'] ,
        "Helsinki": ['Espoo', 'Vantaa', 'Sipoo'] ,
        "Hollola": ['Asikkala', 'Hausjärvi', 'Hämeenlinna', 'Lahti', 'Kärkölä', 'Orimattila'] ,
        "Humppila": ['Forssa', 'Jokioinen', 'Ypäjä', 'Loimaa', 'Punkalaidun', 'Urjala'] ,
        "Hyvinkää": ['Riihimäki', 'Hausjärvi', 'Mäntsälä', 'Tuusula', 'Nurmijärvi', 'Vihti', 'Loppi'] ,
        "Hämeenkyrö": ['Ikaalinen', 'Sastamala', 'Ylöjärvi'] ,
        "Hämeenlinna": ['Akaa', 'Asikkala', 'Hattula', 'Hausjärvi', 'Hollola', 'Janakkala', 'Loppi', 'Padasjoki', 'Pälkäne', 'Tammela', 'Urjala', 'Valkeakoski'] ,
        "Ii": ['Oulu', 'Pudasjärvi', 'Ranua', 'Simo'] ,
        "Iisalmi": ['Kiuruvesi', 'Lapinlahti', 'Kuopio', 'Pielavesi', 'Sonkajärvi', 'Vieremä'] ,
        "Iitti": ['Heinola', 'Kouvola', 'Elimäki', 'Kuusankoski', 'Jaala', 'Lahti', 'Nastola', 'Lapinjärvi', 'Orimattila'] ,
        "Ikaalinen": ['Hämeenkyrö', 'Jämijärvi', 'Kankaanpää', 'Parkano', 'Sastamala', 'Ylöjärvi'] ,
        "Ilmajoki": ['Isokyrö', 'Kurikka', 'Laihia', 'Seinäjoki'] ,
        "Imatra": ['Lappeenranta', 'Ruokolahti'] ,
        "Inari": ['Enontekiö', 'Kittilä', 'Sodankylä', 'Utsjoki'] ,
        "Inkoo": [ 'Raasepori', 'Lohja', 'Siuntio'],
        "Isokyrö": ['Ilmajoki', 'Laihia', 'Vaasa', 'Vöyri', 'Kauhava', 'Seinäjoki'] ,
        "Janakkala": ['Hausjärvi', 'Loppi', 'Riihimäki', 'Hämeenlinna'] ,
        "Joensuu": ['Ilomantsi', 'Kontiolahti', 'Lieksa', 'Rääkkylä', 'Tohmajärvi'] ,
        "Joroinen": ['Juva', 'Leppävirta', 'Pieksämäki', 'Rantasalmi'] ,
        "Joutsa": ['Hartola', 'Hirvensalmi', 'Jyväskylä', 'Kangasniemi', 'Luhanka', 'Pertunmaa', 'Toivakka'] ,
        "Juuka": ['Kuopio', 'Kaavi', 'Kontiolahti', 'Lieksa', 'Nurmes', 'Polvijärvi', 'Rautavaara'] ,
        "Juva": ['Joroinen', 'Mikkeli', 'Pieksämäki', 'Puumala', 'Rantasalmi', 'Sulkava'] ,
        "Jyväskylä": ['Joutsa', 'Toivakka', 'Jämsä', 'Luhanka', 'Muurame', 'Petäjävesi', 'Laukaa', 'Uurainen'] ,
        "Jämsä": ['Juupajoki', 'Jyväskylä', 'Keuruu', 'Kuhmoinen', 'Luhanka', 'Orivesi', 'Petäjävesi'] ,
        "Järvenpää": ['Mäntsälä', 'Sipoo', 'Tuusula'] ,
        "Kaarina": ['Lieto', 'Parainen', 'Paimio', 'Sauvo', 'Turku'] ,
        "Kajaani": ['Paltamo', 'Pyhäntä', 'Siikalatva', 'Sonkajärvi', 'Sotkamo', 'Vaala', 'Vieremä'] ,
        "Kalajoki": ['Alavieska', 'Kokkola', 'Merijärvi', 'Pyhäjoki', 'Sievi', 'Ylivieska'] ,
        "Kangasala": ['Kuhmoinen', 'Lempäälä', 'Orivesi', 'Padasjoki', 'Pälkäne', 'Tampere', 'Valkeakoski'] ,
        "Kangasniemi": ['Hankasalmi', 'Hirvensalmi', 'Joutsa', 'Mikkeli', 'Pieksämäki', 'Toivakka'] ,
        "Kankaanpää": ['Honkajoki', 'Ikaalinen', 'Jämijärvi', 'Karvia', 'Parkano', 'Pomarkku', 'Pori', 'Sastamala', 'Siikainen'] ,
        "Kannus": ['Kalajoki', 'Kokkola', 'Sievi', 'Toholampi'],
        "Karkkila": ['Lohja', 'Loppi', 'Tammela', 'Vihti'] ,
        "Kauhajoki": ['Honkajoki', 'Isojoki', 'Karijoki', 'Karvia', 'Kurikka', 'Teuva'] ,
        "Kauhava": ['Evijärvi', 'Isokyrö', 'Lappajärvi', 'Lapua', 'Seinäjoki', 'Uusikaarlepyy', 'Vöyri'] ,
        "Kaustinen": ['Halsua', 'Kokkola', 'Kruunupyy', 'Veteli'] ,
        "Kemi": ['Keminmaa', 'Simo', 'Tornio'] ,
        "Kemijärvi": ['Pelkosenniemi', 'Salla', 'Posio', 'Rovaniemi'] ,
        "Keminmaa": ['Kemi', 'Simo', 'Tervola', 'Tornio'] ,
        "Kempele": ['Liminka', 'Oulu', 'Tyrnävä'] ,
        "Keuruu": ['Jämsä', 'Multia', 'Petäjävesi', 'Virrat', 'Ähtäri'] ,
        "Kirkkonummi": ['Vihti', 'Siuntio', 'Inkoo'] ,
        "Kitee": ['Parikkala', 'Rääkkylä', 'Savonlinna', 'Tohmajärvi'] ,
        "Kittilä": ['Enontekiö', 'Inari', 'Kolari', 'Muonio', 'Rovaniemi', 'Sodankylä'] ,
        "Kiuruvesi": ['Iisalmi', 'Pielavesi', 'Pyhäjärvi', 'Pyhäntä', 'Vieremä'] ,
        "Kokkola": ['Halsua', 'Kalajoki', 'Kaustinen', 'Kruunupyy', 'Lestijärvi', 'Luoto', 'Toholampi'] ,
        "Kolari": ['Kittilä', 'Muonio', 'Pello', 'Rovaniemi'] ,
        "Kontiolahti": ['Joensuu', 'Juuka', 'Lieksa', 'Polvijärvi'] ,
        "Kotka": ['Hamina', 'Kouvola', 'Pyhtää'],
        "Kouvola": ['Hamina', 'Heinola', 'Iitti', 'Lapinjärvi', 'Loviisa', 'Luumäki', 'Miehikkälä', 'Mäntyharju', 'Pyhtää', 'Savitaipale'] ,
        "Kristiinankaupunki": ['Isojoki', 'Karijoki', 'Merikarvia', 'Närpiö', 'Teuva'] ,
        "Kuhmo": ['Hyrynsalmi', 'Lieksa', 'Nurmes', 'Ristijärvi', 'Sotkamo', 'Suomussalmi'] ,
        "Kuhmoinen": ['Jämsä', 'Kangasala', 'Luhanka', 'Orivesi', 'Padasjoki', 'Sysmä'] ,
        "Kuopio": ['Lapinlahti', 'Iisalmi', 'Leppävirta', 'Rautavaara', 'Siilinjärvi', 'Suonenjoki', 'Tervo', 'Pielavesi', 'Kaavi', 'Juuka', 'Tuusniemi'] ,
        "Kuortane": ['Alajärvi', 'Alavus', 'Lapua', 'Seinäjoki'] ,
        "Kurikka": ['Ilmajoki', 'Karvia', 'Kauhajoki', 'Kihniö', 'Laihia', 'Maalahti', 'Närpiö', 'Parkano', 'Seinäjoki', 'Teuva'] ,
        "Kuusamo": ['Posio', 'Salla', 'Suomussalmi', 'Taivalkoski'] ,
        "Kärsämäki": ['Haapajärvi', 'Haapavesi', 'Pyhäjärvi', 'Pyhäntä', 'Siikalatva'] ,
        "Lahti": ['Asikkala', 'Heinola', 'Hollola', 'Iitti', 'Orimattila'] ,
        "Laihia": ['Ilmajoki', 'Isokyrö', 'Kurikka', 'Maalahti', 'Mustasaari', 'Vaasa'] ,
        "Lappeenranta": ['Imatra', 'Lemi', 'Luumäki', 'Miehikkälä', 'Ruokolahti', 'Taipalsaari'] ,
        "Lapua": ['Alajärvi', 'Kauhava', 'Kuortane', 'Lappajärvi', 'Seinäjoki'] ,
        "Laukaa": ['Hankasalmi', 'Jyväskylä', 'Konnevesi', 'Toivakka', 'Uurainen', 'Äänekoski'] ,
        "Lempäälä": ['Akaa', 'Kangasala', 'Pirkkala', 'Tampere', 'Valkeakoski', 'Vesilahti'] ,
        "Leppävirta": ['Heinävesi', 'Joroinen', 'Kuopio', 'Pieksämäki', 'Suonenjoki', 'Tuusniemi'] ,
        "Lieksa": ['Ilomantsi', 'Joensuu', 'Juuka', 'Kontiolahti', 'Kuhmo', 'Nurmes'] ,
        "Lieto": ['Kaarina', 'Marttila', 'Paimio', 'Pöytyä', 'Turku'] ,
        "Liminka": ['Kempele', 'Lumijoki', 'Muhos', 'Oulu', 'Siikajoki', 'Siikalatva', 'Tyrnävä', 'Vaala'] ,
        "Liperi": ['Heinävesi', 'Joensuu', 'Kontiolahti', 'Polvijärvi', 'Rääkkylä', 'Savonlinna', 'Outokumpu'],
        "Lohja": ['Inkoo', 'Karkkila', 'Raasepori', 'Salo', 'Siuntio', 'Somero', 'Tammela', 'Vihti'] ,
        "Loppi": ['Hyvinkää', 'Hämeenlinna', 'Janakkala', 'Karkkila', 'Riihimäki', 'Tammela', 'Vihti'] ,
        "Loviisa": ['Kouvola', 'Lapinjärvi', 'Myrskylä', 'Porvoo', 'Pyhtää'] ,
        "Luumäki": ['Hamina', 'Kouvola', 'Lappeenranta', 'Lemi', 'Miehikkälä', 'Savitaipale'] ,
        "Marttila": ['Lieto', 'Loimaa', 'Paimio', 'Pöytyä', 'Salo'] ,
        "Masku": ['Mynämäki', 'Nousiainen', 'Rusko', 'Raisio', 'Naantali', 'Taivassalo'],
        "Mikkeli": ['Hirvensalmi', 'Juva', 'Kangasniemi', 'Mäntyharju', 'Pieksämäki', 'Puumala', 'Savitaipale'] ,
        "Muhos": ['Liminka', 'Oulu', 'Siikalatva', 'Tyrnävä', 'Utajärvi', 'Vaala'] ,
        "Muonio": ['Enontekiö', 'Kittilä', 'Kolari'],
        "Mustasaari": ['Laihia', 'Maalahti', 'Vaasa', 'Vöyri'] ,
        "Muurame": ['Jyväskylä'] ,
        "Mäntsälä": ['Kärkölä', 'Orimattila', 'Pukkila', 'Askola', 'Pornainen', 'Sipoo', 'Järvenpää', 'Tuusula', 'Hyvinkää', 'Hausjärvi'] ,
        "Mäntyharju": ['Heinola', 'Hirvensalmi', 'Kouvola', 'Mikkeli', 'Pertunmaa', 'Savitaipale'] ,
        "Nakkila": ['Eura', 'Eurajoki', 'Harjavalta', 'Pori', 'Ulvila'] ,
        "Nokia": ['Hämeenkyrö', 'Pirkkala', 'Sastamala', 'Tampere', 'Vesilahti', 'Ylöjärvi'],
        "Nurmijärvi": ['Espoo', 'Vantaa', 'Tuusula', 'Hyvinkää', 'Vihti'] ,
        "Närpiö": ['Kaskinen', 'Korsnäs', 'Kristiinankaupunki', 'Kurikka', 'Maalahti', 'Teuva'] ,
        "Orivesi": ['Juupajoki', 'Jämsä', 'Kangasala', 'Kuhmoinen', 'Ruovesi', 'Tampere'] ,
        "Oulainen": ['Alavieska', 'Haapavesi', 'Merijärvi', 'Pyhäjoki', 'Raahe', 'Ylivieska'] ,
        "Oulu": ['Hailuoto', 'Ii', 'Kempele', 'Liminka', 'Lumijoki', 'Muhos', 'Pudasjärvi', 'Tyrnävä', 'Utajärvi'] ,
        "Paimio": ['Lieto', 'Kaarina', 'Marttila', 'Salo', 'Sauvo'] ,
        "Paltamo": ['Kajaani', 'Puolanka', 'Ristijärvi', 'Sotkamo', 'Vaala'] ,
        "Parainen": ['Brändö', 'Sottunga', 'Kemiönsaari', 'Sauvo', 'Kaarina', 'Turku', 'Naantali', 'Kustavi'] ,
        "Pedersören kunta": ['Evijärvi', 'Kauhava', 'Kruunupyy', 'Luoto', 'Pietarsaari', 'Uusikaarlepyy'] ,
        "Pello": ['Kolari', 'Ylitornio', 'Rovaniemi'],
        "Perho": ['Alajärvi', 'Halsua', 'Kinnula', 'Kivijärvi', 'Kyyjärvi', 'Lestijärvi', 'Veteli', 'Vimpeli'],
        "Pertunmaa": ['Hartola', 'Heinola', 'Hirvensalmi', 'Mäntyharju', 'Joutsa'] ,
        "Petäjävesi": ['Jyväskylä', 'Jämsä', 'Keuruu', 'Multia', 'Uurainen'] ,
        "Pieksämäki": ['Hankasalmi', 'Joroinen', 'Juva', 'Kangasniemi', 'Leppävirta', 'Mikkeli', 'Rautalampi', 'Suonenjoki'] ,
        "Pielavesi": ['Iisalmi', 'Keitele', 'Kiuruvesi', 'Kuopio', 'Pihtipudas', 'Pyhäjärvi', 'Tervo'] ,
        "Pirkkala": ['Tampere', 'Lempäälä', 'Vesilahti'] ,
        "Pori": ['Noormarkku', 'Lavia', 'Kullaa', 'Luvia'] ,
        "Porvoo": ['Askola', 'Loviisa', 'Myrskylä', 'Pornainen', 'Sipoo'] ,
        "Posio": ['Rovaniemi', 'Kemijärvi', 'Ranua', 'Salla', 'Kuusamo', 'Taivalkoski', 'Pudasjärvi'] ,
        "Pudasjärvi": ['Ii', 'Oulu', 'Posio', 'Puolanka', 'Ranua', 'Suomussalmi', 'Taivalkoski', 'Utajärvi'] ,
        "Puolanka": ['Hyrynsalmi', 'Paltamo', 'Pudasjärvi', 'Ristijärvi', 'Suomussalmi', 'Utajärvi', 'Vaala'] ,
        "Pyhtää": ['Loviisa', 'Kouvola', 'Anjalankoski', 'Elimäki'] ,
        "Pyhäjärvi": ['Haapajärvi', 'Kiuruvesi', 'Kärsämäki', 'Pielavesi', 'Pihtipudas', 'Pyhäntä'] ,
        "Pyhäranta": ['Laitila', 'Rauma', 'Uusikaupunki'] ,
        "Raahe": ['Haapavesi', 'Oulainen', 'Pyhäjoki', 'Siikajoki', 'Siikalatva'] ,
        "Raasepori": ['Hanko', 'Kemiönsaari', 'Salo', 'Inkoo', 'Lohja'] ,
        "Raisio": ['Masku', 'Naantali', 'Rusko', 'Turku'] ,
        "Ranua": ['Ii', 'Simo', 'Tervola', 'Rovaniemi', 'Posio', 'Pudasjärvi'] ,
        "Rauma": ["Eurajoki", "Eura", "Laitila", "Pyhäranta"],
        "Rautavaara": ['Juuka', 'Kuopio', 'Lapinlahti', 'Nurmes', 'Sonkajärvi', 'Sotkamo'] ,
        "Rautjärvi": ['Parikkala', 'Ruokolahti'] ,
        "Riihimäki": ['Janakkala', 'Hausjärvi', 'Hyvinkää', 'Loppi'] ,
        "Ristijärvi": ['Puolanka', 'Hyrynsalmi', 'Kuhmo', 'Sotkamo', 'Paltamo'],
        "Rovaniemi": ['Kittilä', 'Sodankylä', 'Kolari', 'Pello', 'Ylitornio', 'Tervola', 'Ranua', 'Posio', 'Kemijärvi', 'Pelkosenniemi'] ,
        "Ruokolahti": ['Imatra', 'Lappeenranta', 'Parikkala', 'Puumala', 'Rautjärvi', 'Savonlinna', 'Sulkava', 'Taipalsaari'] ,
        "Ruovesi": ['Juupajoki', 'Orivesi', 'Tampere', 'Virrat', 'Ylöjärvi'] ,
        "Saarijärvi": ['Kannonkoski', 'Karstula', 'Multia', 'Soini', 'Uurainen', 'Ähtäri', 'Äänekoski'] ,
        "Salla": ['Kemijärvi', 'Kuusamo', 'Pelkosenniemi', 'Posio', 'Savukoski'] ,
        "Salo": ['Lohja', 'Kemiönsaari', 'Marttila', 'Paimio', 'Raasepori', 'Sauvo', 'Somero'] ,
        "Sastamala": ['Huittinen', 'Hämeenkyrö', 'Ikaalinen', 'Kankaanpää', 'Kokemäki', 'Nokia', 'Pori', 'Punkalaidun', 'Ulvila', 'Urjala', 'Vesilahti'],
        "Savonlinna": ['Enonkoski', 'Heinävesi', 'Kitee', 'Parikkala', 'Rantasalmi', 'Ruokolahti', 'Rääkkylä', 'Sulkava'] ,
        "Seinäjoki": ['Kauhava', 'Lapua', 'Kuortane', 'Alavus', 'Virrat', 'Kihniö', 'Ilmajoki', 'Kurikka', 'Isokyrö'],
        "Sievi": ['Haapajärvi', 'Kalajoki', 'Lestijärvi', 'Nivala', 'Reisjärvi', 'Toholampi', 'Ylivieska'] ,
        "Siikalatva": ['Haapavesi', 'Kajaani', 'Kärsämäki', 'Liminka', 'Muhos', 'Pyhäntä', 'Raahe', 'Siikajoki', 'Vaala'] ,
        "Siilinjärvi": ['Kuopio', 'Lapinlahti'] ,
        "Sipoo": ['Helsinki', 'Vantaa', 'Kerava', 'Tuusula', 'Järvenpää', 'Porvoo', 'Pornainen', 'Mäntsälä'],
        "Sodankylä": ['Inari'] ,
        "Sotkamo": ['Kajaani', 'Kuhmo', 'Nurmes', 'Paltamo', 'Rautavaara', 'Ristijärvi', 'Sonkajärvi'] ,
        "Suomussalmi": ['Taivalkoski', 'Puolanka', 'Hyrynsalmi', 'Kuusamo', 'Pudasjärvi', 'Kuhmo'],
        "Suonenjoki": ['Kuopio', 'Leppävirta', 'Pieksämäki', 'Rautalampi', 'Tervo'] ,
        "Tammela": ['Forssa', 'Hämeenlinna', 'Jokioinen', 'Karkkila', 'Lohja', 'Loppi', 'Somero', 'Urjala'] ,
        "Tampere": ["Ruovesi", "Ylöjärvi", "Pirkkala", "Nokia", "Lempäälä", "Kangasala", "Orivesi"],
        "Tervola": ['Keminmaa', 'Ranua', 'Rovaniemi', 'Simo', 'Tornio', 'Ylitornio'],
        "Teuva": ['Kurikka', 'Kauhajoki', 'Karijoki', 'Kristiinankaupunki', 'Närpiö'] ,
        "Tohmajärvi": ['Joensuu', 'Kitee', 'Rääkkylä'] ,
        "Toivakka": ['Hankasalmi', 'Joutsa', 'Jyväskylä', 'Kangasniemi', 'Laukaa', 'Muurame'] ,
        "Tornio": ['Kemi', 'Keminmaa', 'Tervola', 'Ylitornio'] ,
        "Turku": ['Kaarina', 'Lieto', 'Masku', 'Mynämäki', 'Naantali', 'Nousiainen', 'Parainen', 'Pöytyä', 'Raisio', 'Rusko'] ,
        "Tuusniemi": ['Heinävesi', 'Kaavi', 'Kuopio', 'Leppävirta', 'Outokumpu'] ,
        "Tuusula": ['Hyvinkää', 'Mäntsälä', 'Järvenpää', 'Sipoo', 'Kerava', 'Vantaa', 'Nurmijärvi'] ,
        "Ulvila": ['Harjavalta', 'Kokemäki', 'Nakkila', 'Sastamala'] ,
        "Utsjoki": ['Inari'] ,
        "Uusikaarlepyy": ['Kauhava', 'Pietarsaari', 'Vöyri'] ,
        "Vaala": ['Kajaani', 'Liminka', 'Muhos', 'Paltamo', 'Puolanka', 'Siikalatva', 'Utajärvi'] ,
        "Vaasa": ['Isokyrö', 'Laihia', 'Maalahti', 'Mustasaari', 'Vöyri'],
        "Valkeakoski": ['Akaa', 'Hattula', 'Hämeenlinna', 'Kangasala', 'Lempäälä', 'Pälkäne'] ,
        "Vantaa": ['Helsinki', 'Espoo', 'Nurmijärvi', 'Tuusula', 'Kerava', 'Sipoo'] ,
        "Veteli": ['Evijärvi', 'Halsua', 'Kaustinen', 'Kruunupyy', 'Lappajärvi', 'Vimpeli'] ,
        "Vieremä": ['Iisalmi', 'Kajaani', 'Kiuruvesi', 'Pyhäntä', 'Sonkajärvi'] ,
        "Vihti": ['Karkkila', 'Loppi', 'Hyvinkää', 'Nurmijärvi', 'Espoo', 'Kirkkonummi', 'Siuntio', 'Lohja'] ,
        "Viitasaari": ['Kannonkoski', 'Keitele', 'Kinnula', 'Kivijärvi', 'Pihtipudas', 'Vesanto', 'Äänekoski'] ,
        "Virolahti": ['Hamina', 'Miehikkälä'] ,
        "Vöyri": ['Isokyrö', 'Kauhava', 'Mustasaari', 'Uusikaarlepyy', 'Vaasa'] ,
        "Ylitornio": ['Pello', 'Rovaniemi', 'Tervola', 'Tornio'],
        "Ylöjärvi": ['Hämeenkyrö', 'Ikaalinen', 'Kihniö', 'Parkano', 'Ruovesi', 'Tampere', 'Virrat'] ,
        "Ähtäri": ['Alajärvi', 'Alavus', 'Keuruu', 'Multia', 'Saarijärvi', 'Soini', 'Virrat'] ,
        "Äänekoski": ['Kannonkoski', 'Konnevesi', 'Laukaa', 'Saarijärvi', 'Uurainen', 'Vesanto', 'Viitasaari'] ,
"Anjalankoski": ['Elimäki', 'Hamina', 'Kotka', 'Luumäki', 'Pyhtää'] ,
"Askola": ['Myrskylä', 'Mäntsälä', 'Pornainen', 'Porvoo', 'Pukkila'] ,
"Elimäki": ['Anjalankoski', 'Iitti', 'Kouvola', 'Kuusankoski', 'Lapinjärvi', 'Pyhtää'] ,
"Enonkoski": ['Savonlinna'] ,
"Eura": ['Eurajoki', 'Harjavalta', 'Kokemäki', 'Laitila', 'Mynämäki', 'Nakkila', 'Pöytyä', 'Rauma', 'Säkylä'] ,
"Forssa": ['Jokioinen', 'Tammela', 'Humppila', 'Urjala'] ,
"Haapavesi": ['Haapajärvi', 'Kärsämäki', 'Nivala', 'Oulainen', 'Raahe', 'Siikalatva', 'Ylivieska'] ,
"Halsua": ['Kaustinen', 'Kokkola', 'Lestijärvi', 'Veteli'] ,
"Hanko": ['Kemiönsaari', 'Raasepori'] ,
"Harjavalta": ['Eura', 'Kokemäki', 'Nakkila', 'Ulvila'] ,
"Hattula": ['Hämeenlinna', 'Pälkäne', 'Valkeakoski'] ,
"Hirvensalmi": ['Joutsa', 'Kangasniemi', 'Mikkeli', 'Mäntyharju', 'Pertunmaa'] ,
"Honkajoki": ['Isojoki', 'Kankaanpää', 'Karvia', 'Kauhajoki', 'Siikainen'] ,
"Huittinen": ['Kokemäki', 'Loimaa', 'Punkalaidun', 'Sastamala', 'Säkylä'] ,
"Hyrynsalmi": ['Kuhmo', 'Puolanka', 'Ristijärvi', 'Suomussalmi'] ,
"Hämeenkoski": ['Asikkala', 'Hausjärvi', 'Hollola', 'Hämeenlinna', 'Kärkölä'] ,
"Ilomantsi": ['Joensuu', 'Lieksa'] ,
"Isojoki": ['Honkajoki', 'Karijoki', 'Kauhajoki', 'Kristiinankaupunki', 'Merikarvia', 'Siikainen'] ,
"Jaala": ['Heinola', 'Iitti', 'Kuusankoski', 'Mäntyharju'] ,
"Jokioinen": ['Tammela', 'Somero', 'Ypäjä', 'Humppila'] ,
"Juupajoki": ['Jämsä', 'Orivesi', 'Ruovesi'] ,
"Jämijärvi": ['Ikaalinen', 'Kankaanpää', 'Parkano'] ,
"Kaavi": ['Kuopio', 'Juuka', 'Outokumpu', 'Polvijärvi', 'Tuusniemi'] ,
"Kannonkoski": ['Karstula', 'Kivijärvi', 'Saarijärvi', 'Viitasaari', 'Äänekoski'] ,
"Karijoki": ['Isojoki', 'Kauhajoki', 'Kristiinankaupunki', 'Teuva'] ,
"Karstula": ['Kannonkoski', 'Kivijärvi', 'Kyyjärvi', 'Saarijärvi', 'Soini'] ,
"Karvia": ['Honkajoki', 'Kankaanpää', 'Kauhajoki', 'Kurikka', 'Parkano'] ,
"Keitele": ['Pielavesi', 'Pihtipudas', 'Tervo', 'Vesanto', 'Viitasaari'] ,
"Kemiönsaari": ['Salo', 'Raasepori', 'Hanko', 'Parainen', 'Sauvo'] ,
"Kihniö": ['Kurikka', 'Ylöjärvi', 'Parkano', 'Seinäjoki', 'Virrat'] ,
"Kinnula": ['Kivijärvi', 'Lestijärvi', 'Pihtipudas', 'Reisjärvi', 'Viitasaari'] ,
"Kivijärvi": ['Kannonkoski', 'Karstula', 'Kinnula', 'Kyyjärvi', 'Viitasaari'] ,
"Kokemäki": ['Eura', 'Harjavalta', 'Huittinen', 'Pori', 'Sastamala', 'Säkylä', 'Ulvila'] ,
"Konnevesi": ['Hankasalmi', 'Laukaa', 'Rautalampi', 'Vesanto', 'Äänekoski'] ,
"Korsnäs": ['Maalahti', 'Närpiö'] ,
"Kruunupyy": ['Evijärvi', 'Kaustinen', 'Kokkola', 'Luoto', 'Veteli'] ,
"Kullaa": ['Harjavalta', 'Kokemäki', 'Lavia', 'Nakkila', 'Noormarkku', 'Pori'] ,
"Kustavi": ['Brändö', 'Parainen', 'Naantali', 'Taivassalo', 'Uusikaupunki'] ,
"Kuusankoski": ['Elimäki', 'Iitti', 'Jaala', 'Kouvola'] ,
"Kyyjärvi": ['Alajärvi', 'Karstula', 'Kivijärvi', 'Soini'] ,
"Kärkölä": ['Hausjärvi', 'Hollola', 'Mäntsälä', 'Orimattila'] ,
"Laitila": ['Eura', 'Mynämäki', 'Pyhäranta', 'Rauma', 'Uusikaupunki', 'Vehmaa'] ,
"Lammi": ['Asikkala', 'Hausjärvi', 'Hämeenkoski', 'Janakkala', 'Kärkölä', 'Padasjoki'] ,
"Lapinjärvi": ['Iitti', 'Kouvola', 'Loviisa', 'Myrskylä', 'Orimattila'] ,
"Lapinlahti": ['Iisalmi', 'Kuopio', 'Rautavaara', 'Siilinjärvi', 'Sonkajärvi'] ,
"Lappajärvi": ['Alajärvi', 'Evijärvi', 'Kauhava', 'Lapua', 'Veteli', 'Vimpeli'] ,
"Lavia": ['Kankaanpää', 'Kokemäki', 'Pori', 'Pomarkku', 'Sastamala', 'Ulvila'] ,
"Lemi": ['Lappeenranta', 'Luumäki', 'Savitaipale', 'Taipalsaari'] ,
"Lestijärvi": ['Halsua', 'Kinnula', 'Kokkola', 'Reisjärvi', 'Sievi', 'Toholampi'] ,
"Loimaa": ['Huittinen', 'Humppila', 'Marttila', 'Oripää', 'Punkalaidun', 'Pöytyä', 'Somero', 'Säkylä', 'Ypäjä'] ,
"Luhanka": ['Hartola', 'Joutsa', 'Jyväskylä', 'Jämsä', 'Kuhmoinen', 'Sysmä'] ,
"Lumijoki": ['Hailuoto', 'Liminka', 'Oulu', 'Siikajoki'] ,
"Luoto": ['Kokkola', 'Kruunupyy', 'Pietarsaari'] ,
"Luvia": ['Eurajoki', 'Nakkila', 'Pori'] ,
"Maalahti": ['Korsnäs', 'Kurikka', 'Laihia', 'Mustasaari', 'Närpiö'] ,
"Merijärvi": ['Alavieska', 'Kalajoki', 'Oulainen', 'Ylivieska', 'Pyhäjoki'] ,
"Merikarvia": ['Isojoki', 'Kristiinankaupunki', 'Pomarkku', 'Pori', 'Siikainen'] ,
"Multia": ['Keuruu', 'Petäjävesi', 'Saarijärvi', 'Uurainen', 'Ähtäri'] ,
"Mynämäki": ['Eura', 'Laitila', 'Masku', 'Nousiainen', 'Pöytyä', 'Rusko', 'Taivassalo', 'Turku', 'Vehmaa'] ,
"Myrskylä": ['Askola', 'Porvoo', 'Pukkila', 'Orimattila', 'Lapinjärvi', 'Loviisa'] ,
"Naantali": ['Parainen', 'Masku', 'Raisio', 'Taivassalo', 'Turku'] ,
"Nastola": ['Asikkala', 'Heinola', 'Hollola', 'Iitti', 'Lahti', 'Orimattila'] ,
"Nivala": ['Haapajärvi', 'Haapavesi', 'Sievi', 'Ylivieska'] ,
"Noormarkku": ['Lavia', 'Pomarkku', 'Pori', 'Ulvila'] ,
"Nousiainen": ['Masku', 'Raisio', 'Mynämäki', 'Pöytyä', 'Rusko', 'Turku'] ,
"Nurmes": ['Juuka', 'Lieksa', 'Kuhmo', 'Sotkamo', 'Rautavaara'] ,
"Orimattila": ['Hollola', 'Iitti', 'Kärkölä', 'Lahti', 'Lapinjärvi', 'Myrskylä', 'Mäntsälä', 'Pukkila'] ,
"Outokumpu": ['Polvijärvi', 'Kaavi', 'Tuusniemi', 'Heinävesi'] ,
"Padasjoki": ['Asikkala', 'Hämeenlinna', 'Kangasala', 'Kuhmoinen', 'Pälkäne', 'Sysmä'] ,
"Parikkala": ['Kitee', 'Rautjärvi', 'Ruokolahti', 'Savonlinna'] ,
"Parkano": ['Ikaalinen', 'Jämijärvi', 'Kankaanpää', 'Karvia', 'Kihniö', 'Kurikka', 'Ylöjärvi'] ,
"Pelkosenniemi": ['Kemijärvi', 'Rovaniemi', 'Salla', 'Savukoski', 'Sodankylä'] ,
"Pietarsaari": ['Luoto', 'Uusikaarlepyy'] ,
"Pihtipudas": ['Haapajärvi', 'Keitele', 'Kinnula', 'Pielavesi', 'Pyhäjärvi', 'Reisjärvi', 'Viitasaari'] ,
"Polvijärvi": ['Juuka', 'Kaavi', 'Kontiolahti', 'Outokumpu'] ,
"Pomarkku": ['Kankaanpää', 'Merikarvia', 'Pori', 'Siikainen'] ,
"Pornainen": ['Askola', 'Mäntsälä', 'Porvoo', 'Sipoo'] ,
"Pukkila": ['Orimattila', 'Myrskylä', 'Askola', 'Mäntsälä'] ,
"Punkalaidun": ['Huittinen', 'Humppila', 'Loimaa', 'Urjala', 'Sastamala'] ,
"Puumala": ['Juva', 'Mikkeli', 'Ruokolahti', 'Savitaipale', 'Sulkava', 'Taipalsaari'] ,
"Pyhäntä": ['Kajaani', 'Kiuruvesi', 'Kärsämäki', 'Pyhäjärvi', 'Siikalatva', 'Vieremä'] ,
"Pälkäne": ['Hattula', 'Hämeenlinna', 'Kangasala', 'Padasjoki', 'Valkeakoski'] ,
"Pöytyä": ['Eura', 'Lieto', 'Loimaa', 'Marttila', 'Mynämäki', 'Oripää', 'Säkylä'] ,
"Rantasalmi": ['Joroinen', 'Juva', 'Sulkava'] ,
"Rautalampi": ['Hankasalmi', 'Konnevesi', 'Pieksämäki', 'Suonenjoki', 'Tervo', 'Vesanto'] ,
"Reisjärvi": ['Haapajärvi', 'Kinnula', 'Lestijärvi', 'Pihtipudas', 'Sievi'] ,
"Rääkkylä": ['Joensuu', 'Kitee', 'Savonlinna', 'Tohmajärvi'] ,
"Sauvo": ['Kaarina', 'Kemiönsaari', 'Parainen', 'Paimio', 'Salo'] ,
"Savitaipale": ['Kouvola', 'Lemi', 'Luumäki', 'Mikkeli', 'Mäntyharju', 'Puumala', 'Taipalsaari'] ,
"Savukoski": ['Pelkosenniemi', 'Salla', 'Sodankylä'] ,
"Siikainen": ['Honkajoki', 'Isojoki', 'Kankaanpää', 'Merikarvia', 'Pomarkku', 'Pori'] ,
"Siikajoki": ['Hailuoto', 'Liminka', 'Lumijoki', 'Raahe', 'Siikalatva'] ,
"Siuntio": ['Inkoo', 'Kirkkonummi', 'Lohja', 'Vihti'] ,
"Soini": ['Alajärvi', 'Karstula', 'Kyyjärvi', 'Saarijärvi', 'Ähtäri'] ,
"Somero": ['Jokioinen', 'Lohja', 'Loimaa', 'Salo', 'Tammela', 'Ypäjä'] ,
"Sonkajärvi": ['Iisalmi', 'Kajaani', 'Lapinlahti', 'Rautavaara', 'Sotkamo', 'Vieremä'] ,
"Sulkava": ['Juva', 'Puumala', 'Rantasalmi', 'Ruokolahti', 'Savonlinna'] ,
"Sysmä": ['Asikkala', 'Hartola', 'Heinola', 'Kuhmoinen', 'Luhanka', 'Padasjoki'] ,
"Taivalkoski": ['Kuusamo', 'Posio', 'Pudasjärvi', 'Suomussalmi'] ,
"Taivassalo": ['Kustavi', 'Masku', 'Mynämäki', 'Naantali', 'Uusikaupunki', 'Vehmaa'] ,
"Tervo": ['Keitele', 'Kuopio', 'Pielavesi', 'Rautalampi', 'Suonenjoki', 'Vesanto'] ,
"Toholampi": ['Kokkola', 'Lestijärvi', 'Sievi'] ,
"Tyrnävä": ['Kempele', 'Liminka', 'Muhos', 'Oulu'] ,
"Urjala": ['Akaa', 'Forssa', 'Humppila', 'Hämeenlinna', 'Punkalaidun', 'Sastamala', 'Tammela', 'Vesilahti'] ,
"Utajärvi": ['Muhos', 'Oulu', 'Pudasjärvi', 'Puolanka', 'Vaala'] ,
"Uurainen": ['Jyväskylä', 'Laukaa', 'Multia', 'Petäjävesi', 'Saarijärvi', 'Äänekoski'] ,
"Vesanto": ['Keitele', 'Konnevesi', 'Rautalampi', 'Tervo', 'Viitasaari', 'Äänekoski'] ,
"Vesilahti": ['Akaa', 'Lempäälä', 'Pirkkala', 'Sastamala', 'Urjala'] ,
"Vimpeli": ['Alajärvi', 'Lappajärvi', 'Veteli'] ,
"Virrat": ['Alavus', 'Keuruu', 'Kihniö', 'Ruovesi', 'Seinäjoki', 'Ylöjärvi', 'Ähtäri'] ,
"Ylivieska": ['Alavieska', 'Haapavesi', 'Kalajoki', 'Nivala', 'Oulainen', 'Merijärvi', 'Sievi'] ,
"Ypäjä": ['Jokioinen', 'Somero', 'Loimaa', 'Humppila'] ,
"Hankasalmi": ['Kangasniemi', 'Konnevesi', 'Laukaa', 'Pieksämäki', 'Rautalampi', 'Toivakka'],
"Heinävesi": ['Savonlinna', 'Varkaus', 'Leppävirta', 'Tuusniemi', 'Outokumpu', 'Liperi'],
"Kaskinen": ['Närpiö'],
"Kauniainen": ['Espoo'],
"Kerava": ["Tuusula", "Vantaa", "Sipoo"],
"Miehikkälä": ['Hamina', 'Kouvola', 'Lappeenranta', 'Luumäki', 'Virolahti'],
"Pyhäjoki": ['Kalajoki', 'Merijärvi', 'Oulainen', 'Raahe'],
"Rusko": ['Turku', 'Raisio', 'Masku', 'Nousiainen'],
"Simo": ['Ii', 'Kemi', 'Keminmaa', 'Ranua', 'Tervola'],
"Taipalsaari": ['Lappeenranta', 'Lemi', 'Puumala', 'Ruokolahti', 'Savitaipale'],
"Uusikaupunki": ['Pyhäranta', 'Laitila', 'Vehmaa', 'Taivassalo', 'Kustavi'],
"Oripää": ['Loimaa', 'Pöytyä', 'Säkylä'],
"Säkylä": ['Eura', 'Huittinen', 'Kokemäki', 'Loimaa', 'Oripää', 'Pöytyä'],
"Brändö": ['Kumlinge', 'Kustavi', 'Parainen', 'Sottunga'],
"Varkaus": ['Heinävesi', 'Joroinen', 'Leppävirta', 'Rantasalmi', 'Savonlinna'],
"Vehmaa": ['Laitila', 'Mynämäki', 'Taivassalo', 'Uusikaupunki'],
"Kumlinge": ['Brändö', 'Saltvik', 'Saltvik', 'Sottunga', 'Vårdö'],
"Sottunga": ['Brändö', 'Föglö', 'Kumlinge', 'Kökar', 'Parainen', 'Vårdö'],
"Föglö": ['Sottunga', 'Lemland', 'Lumparland', 'Kökar'],
"Kökar": ['Föglö', 'Parainen', 'Sottunga'],
"Lemland": ['Föglö', 'Jomala', 'Lumparland', 'Maarianhamina', 'Sund'],
"Lumparland": ['Föglö', 'Jomala', 'Lemland', 'Sund', 'Vårdö'],
"Jomala": ['Finström', 'Hammarland', 'Lemland', 'Lumparland', 'Maarianhamina', 'Sund'],
"Maarianhamina": ['Jomala', 'Lemland'],
"Saltvik": ['Finström', 'Geta', 'Kumlinge', 'Sund', 'Vårdö'],
"Sund": ['Finström', 'Jomala', 'Lemland', 'Lumparland', 'Saltvik', 'Vårdö'],
"Vårdö": ['Föglö', 'Kumlinge', 'Lumparland', 'Saltvik', 'Sottunga', 'Sund'],
"Finström": ['Geta', 'Saltvik', 'Hammarland', 'Jomala', 'Sund'],
"Geta": ['Finström', 'Saltvik', 'Hammarland'],
"Hammarland": ['Geta', 'Finström']
    }

